### ISSUE TITLE
goBackToMain 함수

### ISSUE THREAD

**Issue by SeoWonJung** [kahyeonkim/se__project#11]
각 기능별 selectMenu함수에서  go back to main선택했을 때 따로 goBackToMain 함수가 실행되는게 아니라 그냥 while문을 빠져나와서 메인화면으로 돌아오게 했는데 이렇게 해도 괜찮을까 ?

**Comment by toto9230** [comment]
웅! 그렇게 하는게 더 간단할거같아!
