### ISSUE TITLE
Accout Book 날짜 type 변경

### ISSUE THREAD

**Issue by kahyeonkim** [kahyeonkim/se__project#3]
수빈언니~~ Accout Book 날짜 type date에서 String으로 바꿨는데 언니 code가 나한테 없어서ㅠㅠ 잘못 수정한거 있는지 봐죵!!

**Comment by soobeeny** [comment]
웅 맞아! String으로 하려고 했어! ㅎㅎ 오늘 account부분 완성해서 push했어~!!

**Comment by soobeeny** [comment]
근데 어떻게 resolve하는거야? ㅋㅋ 그냥 이렇게하면 resolve가 된건가 ㅎㅎ
