### ISSUE TITLE
파일 이클립스에서 import할 경우 한글 깨짐 문제 발생

### ISSUE THREAD

**Issue by soobeeny** [kahyeonkim/se__project#4]
오늘 서버에 있는 파일 받아서 자바로 import하니까 한글은 다 깨지더라고.

import할 때 인코딩을 utf-8로 하면 된다는데 일단은,  메모장에서 열어서 그냥 한글 있는 부분 다시 고쳐넣었는데 다들 import할 때 조심해!

**Comment by toto9230** [comment]
나두 한글 깨져서 utf-8로 했는데
나중에는 주석 다 지우고
메뉴도 영어로 출력하게하는게 나을듯?

**Comment by kahyeonkim** [comment]
utf-8 이게 뭔지 모르겠다ㅜㅜㅜ 내일 알려죵:) 아니면 지영언니 말대로 영어로 출력하는게 나을거같기두해!!ㅎㅎ

**Comment by SeoWonJung** [comment]
영어로 출력하자

**Comment by kahyeonkim** [comment]
영어사용 해결
