### ISSUE TITLE
accountBook 실행결과

### ISSUE THREAD

**Issue by soobeeny** [kahyeonkim/se__project#5]
메인에서 가계부 메뉴들어가서, 생성하면 생성된 가계부 내용이 나오잖아! 

근데 전체 가계부 list를 출력하면 정상적으로 나오는데 생성했을 때 생성된 내용 하나만 나오는거에서 전에 생성한 가계부 내용이나와..! 

public void create(PurchaseInfo purchaseInfo) {
		int purchaseNum=0;
		purchaseInfos.add(purchaseInfo);
		printAccountList(purchaseNum, purchaseInfo);
		purchaseNum++;
	}

	private void printAccountList(int purchaseNum,PurchaseInfo purchaseinfo) {
		purchaseInfos.get(purchaseNum).printList();
	}

이부분에서 오류난건가?

**Comment by kahyeonkim** [comment]
버그 해결
