### ISSUE TITLE
계산기 정확도 문제.

### ISSUE THREAD

**Issue by toto9230** [kahyeonkim/se__project#6]
계산기 변환기 기능에서 변환기가 얼마나 정확하게 할까???
예를 들어서 
kg을 pound로 변환할 때 kg * 2.204623하면 되는데
처음에 코딩했을때는 kg *2.2까지만 했었거든
그냥 소수점 6자리까지 쓸까봐 ㅎ ㅎ 정확해지게!

**Comment by SeoWonJung** [comment]
응 그게 더 좋을거같아ㅎㅎ
