### ISSUE TITLE
back to main

### ISSUE THREAD

**Issue by toto9230** [kahyeonkim/se__project#7]
메인 메뉴로 돌아가는 부분
calculator에서는 
1.사칙연산 2. 변환기 고르는 부분에만 넣고,
그 하위 메뉴들에는 해당하는 상위메뉴로 돌아가게 하려구
그게 낫겠지 ㅎㅎ

**Comment by kahyeonkim** [comment]
그게좋을거같음ㅎㅎ 이거는 그렇게하구 close하까??
