### ISSUE TITLE
메인부분 refactoring

### ISSUE THREAD

**Issue by soobeeny** [kahyeonkim/se__project#9]
메인에서 메모나 가계부 생성할 때, 내용받아오고 scan받는 부분 너무 기니까 함수로 뽑아내는 거 어때??

**Comment by SeoWonJung** [comment]
scan.nextLine() 하는 이 부분만 함수로 만들자는거야 ?  저거는 뽑아내도 길이는 비슷하지 않을까...?

**Comment by SeoWonJung** [comment]
scan으로 그대로 두자

**Comment by kahyeonkim** [comment]
뽑아냄해결
